# my global config
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "test-1"
    static_configs:
      - targets: ["13.233.86.120:9100"]

  - job_name: "test-2"
    static_configs:
      - targets: ["13.233.113.130:9100"]

  - job_name: "test-server/ Prometheus"
    static_configs:
      - targets: ["65.0.81.122:9100"]
